/* Chapter Two — camera.js | permission prewarm + capture */
let cameraStream=null,cameraCountdownTimer=null,cameraBusy=false,cameraPermissionStream=null;
const cameraEl=()=>document.getElementById("camera"),canvasEl=()=>document.getElementById("captureCanvas"),statusEl=()=>document.getElementById("cameraStatus"),countdownEl=()=>document.getElementById("cameraCountdown");
async function prepareCameraPermission(){try{if(!navigator.mediaDevices?.getUserMedia)return false;if(cameraPermissionStream)return true;cameraPermissionStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"user"}},audio:false});cameraPermissionStream.getTracks().forEach(t=>t.stop());cameraPermissionStream=null;console.log("📸 Camera permission ready");return true;}catch(e){console.warn("Camera permission not granted:",e);return false;}}
async function startCamera(){const video=cameraEl(),status=statusEl(),count=countdownEl();if(!video)return;try{cameraBusy=false;stopCamera();if(!navigator.mediaDevices?.getUserMedia)throw new Error("Camera API unavailable");if(status)status.textContent="Starting camera... 📸";cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"user"},width:{ideal:1280},height:{ideal:1280}},audio:false});video.srcObject=cameraStream;video.muted=true;video.playsInline=true;video.autoplay=true;await waitForVideoReady(video);await video.play();if(status)status.textContent="Get ready... 📸";await runCameraCountdown();}catch(error){console.error("Camera error:",error);stopCamera();if(status)status.textContent="Camera permission nahi mili. Browser mein Camera Allow karo 📸";if(count)count.textContent="📷";}}
function waitForVideoReady(video){return new Promise((resolve,reject)=>{if(video.videoWidth>0&&video.videoHeight>0){resolve();return;}const timeout=setTimeout(()=>{cleanup();reject(new Error("Camera video did not become ready."));},8000);function ready(){if(video.videoWidth>0&&video.videoHeight>0){cleanup();resolve();}}function cleanup(){clearTimeout(timeout);video.removeEventListener("loadedmetadata",ready);video.removeEventListener("canplay",ready);video.removeEventListener("playing",ready);}video.addEventListener("loadedmetadata",ready);video.addEventListener("canplay",ready);video.addEventListener("playing",ready);});}
function runCameraCountdown(){return new Promise(resolve=>{let n=3;const count=countdownEl(),status=statusEl();clearInterval(cameraCountdownTimer);if(count)count.textContent=n;cameraCountdownTimer=setInterval(()=>{n--;if(n>0){if(count)count.textContent=n;}else{clearInterval(cameraCountdownTimer);cameraCountdownTimer=null;if(count)count.textContent="❤️";if(status)status.textContent="Smile! 📸";setTimeout(async()=>{await captureSelfie();resolve();},500);}},1000);});}
async function captureSelfie(){if(cameraBusy)return;const video=cameraEl(),canvas=canvasEl(),status=statusEl();if(!video||!canvas||!cameraStream)return;if(video.videoWidth===0||video.videoHeight===0)return;cameraBusy=true;try{const size=Math.min(video.videoWidth,video.videoHeight);canvas.width=size;canvas.height=size;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Canvas unsupported");const sx=(video.videoWidth-size)/2,sy=(video.videoHeight-size)/2;ctx.save();ctx.translate(size,0);ctx.scale(-1,1);ctx.drawImage(video,sx,sy,size,size,0,0,size,size);ctx.restore();const blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/jpeg",.92));if(!blob)throw new Error("Could not create image");stopCamera();const previewUrl=URL.createObjectURL(blob),selfie=document.getElementById("selfieImage");if(selfie)selfie.src=previewUrl;localStorage.setItem("latestSelfie",previewUrl);if(status)status.textContent="Memory captured! ❤️";if(typeof saveSelfie==="function"){try{await saveSelfie(blob);}catch(e){console.warn("Supabase upload skipped:",e);}}if(typeof showLatestSelfie==="function")showLatestSelfie();if(typeof showPage==="function")showPage("selfiePage");}catch(error){console.error("Capture error:",error);if(status)status.textContent="Photo capture nahi ho saki. Dobara try karo 📸";}finally{cameraBusy=false;}}
function stopCamera(){clearInterval(cameraCountdownTimer);cameraCountdownTimer=null;if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null;}const video=cameraEl();if(video){video.pause();video.srcObject=null;}}
function openCameraPage(){if(typeof showPage==="function")showPage("cameraPage");setTimeout(startCamera,300);}
console.log("📸 camera.js loaded");