/* Chapter Two — Leaflet + OSRM location map */
const MY_LOCATION={lat:24.989972,lng:67.057583};
const HER_FALLBACK_LOCATION={lat:24.96215102611671,lng:67.05567540257583};
const FALLBACK_DISTANCE_MILES=1.92;
let prewarmedHerLocation=null,lastLiveHerLocation=null,locationMap=null,hisMarker=null,herMarker=null,routeLine=null,routeAnimationTimer=null,locationRequestInFlight=false,locationPrewarmPromise=null;
function distanceMiles(a,b){const R=3958.7613,toRad=v=>v*Math.PI/180,dLat=toRad(b.lat-a.lat),dLng=toRad(b.lng-a.lng),x=Math.sin(dLat/2)**2+Math.cos(toRad(a.lat))*Math.cos(toRad(b.lat))*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
function mapStyle(){if(document.getElementById("leafletLocationStyles"))return;const s=document.createElement("style");s.id="leafletLocationStyles";s.textContent=`#loveMap{width:100%;aspect-ratio:16/9;border-radius:22px;overflow:hidden;margin:18px 0;box-shadow:0 18px 45px rgba(0,0,0,.28);border:1px solid rgba(255,255,255,.2)}.mapDistance{font-weight:700;font-size:1.35rem;margin:10px 0 16px;text-align:center}.homeMarker{width:38px;height:38px;border-radius:50%;display:flex;align-items:center;justify-content:center;background:#ff4d6d;border:3px solid #fff;box-shadow:0 4px 16px rgba(0,0,0,.3);font-size:19px}`;document.head.appendChild(s);}
function markerIcon(emoji){return L.divIcon({className:"",html:`<div class="homeMarker">${emoji}</div>`,iconSize:[38,38],iconAnchor:[19,19],popupAnchor:[0,-18]});}
function initLocationMap(){mapStyle();const el=document.getElementById("loveMap");if(!el||typeof L==="undefined")return null;if(!locationMap){locationMap=L.map(el,{zoomControl:true,scrollWheelZoom:true}).setView([MY_LOCATION.lat,MY_LOCATION.lng],13);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(locationMap);hisMarker=L.marker([MY_LOCATION.lat,MY_LOCATION.lng],{icon:markerIcon("🏠")}).addTo(locationMap).bindPopup("His Home");herMarker=L.marker([HER_FALLBACK_LOCATION.lat,HER_FALLBACK_LOCATION.lng],{icon:markerIcon("❤️")}).addTo(locationMap).bindPopup("Your Home");}setTimeout(()=>locationMap.invalidateSize(),100);return locationMap;}
function drawAnimatedRoute(coords){if(!locationMap||!coords||coords.length<2)return;clearInterval(routeAnimationTimer);if(routeLine)locationMap.removeLayer(routeLine);const points=coords.map(p=>[p[1],p[0]]);routeLine=L.polyline([],{color:"#ff4d6d",weight:6,opacity:.9,lineCap:"round",lineJoin:"round"}).addTo(locationMap);let i=0;routeAnimationTimer=setInterval(()=>{routeLine.setLatLngs(points.slice(0,++i));if(i>=points.length){clearInterval(routeAnimationTimer);routeAnimationTimer=null;}},Math.max(12,Math.min(45,1800/points.length)));}
async function fetchRoute(herLocation){const start=`${MY_LOCATION.lng},${MY_LOCATION.lat}`,end=`${herLocation.lng},${herLocation.lat}`;try{const res=await fetch(`https://router.project-osrm.org/route/v1/driving/${start};${end}?overview=full&geometries=geojson`);if(!res.ok)throw new Error("Routing service unavailable");const data=await res.json();const route=data.routes?.[0];if(!route)throw new Error("No route");const d=document.getElementById("distanceValue");if(d)d.textContent=`${(route.distance/1609.344).toFixed(2)} miles`;drawAnimatedRoute(route.geometry.coordinates);if(locationMap)locationMap.fitBounds(L.latLngBounds(route.geometry.coordinates.map(p=>[p[1],p[0]])),{padding:[35,35]});}catch(e){const d=document.getElementById("distanceValue");if(d)d.textContent=`${distanceMiles(MY_LOCATION,herLocation).toFixed(2)} miles`;drawAnimatedRoute([[MY_LOCATION.lng,MY_LOCATION.lat],[herLocation.lng,herLocation.lat]]);}}
function renderLocationScene(herLocation,live=false){const map=initLocationMap();if(herMarker)herMarker.setLatLng([herLocation.lat,herLocation.lng]);if(live)lastLiveHerLocation={...herLocation};const btn=document.getElementById("locationPermissionBtn"),cont=document.getElementById("locationContinue"),distance=document.getElementById("distanceValue");if(btn)btn.classList.add("hidden");if(cont)cont.classList.remove("hidden");if(distance&&!live)distance.textContent=`${FALLBACK_DISTANCE_MILES.toFixed(2)} miles`;setTimeout(()=>{if(map)map.invalidateSize();fetchRoute(herLocation);},180);}
function requestHerLocation(){if(prewarmedHerLocation){const loc={...prewarmedHerLocation};prewarmedHerLocation=null;renderLocationScene(loc,true);return;}if(locationRequestInFlight)return;if(locationPrewarmPromise){locationRequestInFlight=true;locationPrewarmPromise.then(()=>{locationRequestInFlight=false;if(prewarmedHerLocation){const loc={...prewarmedHerLocation};prewarmedHerLocation=null;renderLocationScene(loc,true);}else renderLocationScene(HER_FALLBACK_LOCATION,false);});return;}if(!navigator.geolocation){renderLocationScene(HER_FALLBACK_LOCATION,false);return;}locationRequestInFlight=true;navigator.geolocation.getCurrentPosition(p=>{locationRequestInFlight=false;renderLocationScene({lat:p.coords.latitude,lng:p.coords.longitude},true);},()=>{locationRequestInFlight=false;renderLocationScene(HER_FALLBACK_LOCATION,false);},{enableHighAccuracy:true,timeout:10000,maximumAge:30000});}
function prepareLocationPermission(){if(!navigator.geolocation)return Promise.resolve(false);if(locationPrewarmPromise)return locationPrewarmPromise;locationPrewarmPromise=new Promise(resolve=>navigator.geolocation.getCurrentPosition(p=>{prewarmedHerLocation={lat:p.coords.latitude,lng:p.coords.longitude};lastLiveHerLocation={...prewarmedHerLocation};resolve(true);},()=>resolve(false),{enableHighAccuracy:true,timeout:10000,maximumAge:30000}));return locationPrewarmPromise;}
function getHerLiveLocation(){return lastLiveHerLocation?{...lastLiveHerLocation}:null;}
function startLocationScene(){requestHerLocation();}
console.log("📍 Leaflet location map loaded — clean UI + location prewarm");