/* Chapter Two — location.js | permission prewarm + distance */
const MY_LOCATION={lat:24.989972,lng:67.057583};
const HER_FALLBACK_LOCATION={lat:24.96215102611671,lng:67.05567540257583};
let prewarmedHerLocation=null;
function distanceKm(a,b){const R=6371,toRad=v=>v*Math.PI/180,dLat=toRad(b.lat-a.lat),dLng=toRad(b.lng-a.lng),x=Math.sin(dLat/2)**2+Math.cos(toRad(a.lat))*Math.cos(toRad(b.lat))*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
function renderLocationScene(herLocation,live=false){let page=document.getElementById("locationPage");if(!page)return;const km=distanceKm(MY_LOCATION,herLocation),distance=document.getElementById("distanceValue"),mode=document.getElementById("herLocationStatus"),status=document.getElementById("locationStatus"),btn=document.getElementById("locationPermissionBtn"),cont=document.getElementById("locationContinue");if(distance)distance.textContent=km<1?`${Math.round(km*1000)} m`:`${km.toFixed(1)} km`;if(mode)mode.textContent=live?"Live location received 📍":"Using saved location";if(status)status.textContent=live?"Location ready ❤️":"Live location unavailable — using saved location.";if(btn)btn.classList.add("hidden");if(cont)cont.classList.remove("hidden");if(typeof showPage==="function")showPage("locationPage");}
function requestHerLocation(){if(prewarmedHerLocation){renderLocationScene(prewarmedHerLocation,true);return;}if(!navigator.geolocation){renderLocationScene(HER_FALLBACK_LOCATION,false);return;}navigator.geolocation.getCurrentPosition(p=>{prewarmedHerLocation={lat:p.coords.latitude,lng:p.coords.longitude};renderLocationScene(prewarmedHerLocation,true);},()=>renderLocationScene(HER_FALLBACK_LOCATION,false),{enableHighAccuracy:false,timeout:5000,maximumAge:300000});}
function prepareLocationPermission(){if(!navigator.geolocation)return Promise.resolve(false);return new Promise(resolve=>{navigator.geolocation.getCurrentPosition(p=>{prewarmedHerLocation={lat:p.coords.latitude,lng:p.coords.longitude};console.log("📍 Location permission ready");resolve(true);},e=>{console.warn("Location permission not granted:",e.message);resolve(false);},{enableHighAccuracy:false,timeout:5000,maximumAge:300000});});}
function startLocationScene(){requestHerLocation();}
console.log("📍 location.js loaded");