/* Chapter Two — location.js | instant fallback + miles */
const MY_LOCATION={lat:24.989972,lng:67.057583};
const HER_FALLBACK_LOCATION={lat:24.96215102611671,lng:67.05567540257583};
const FALLBACK_DISTANCE_MILES=1.92;
let prewarmedHerLocation=null;
function distanceMiles(a,b){const R=3958.7613,toRad=v=>v*Math.PI/180,dLat=toRad(b.lat-a.lat),dLng=toRad(b.lng-a.lng),x=Math.sin(dLat/2)**2+Math.cos(toRad(a.lat))*Math.cos(toRad(b.lat))*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
function renderLocationScene(herLocation,live=false){let page=document.getElementById("locationPage");if(!page)return;const miles=live?distanceMiles(MY_LOCATION,herLocation):FALLBACK_DISTANCE_MILES,distance=document.getElementById("distanceValue"),mode=document.getElementById("herLocationStatus"),status=document.getElementById("locationStatus"),btn=document.getElementById("locationPermissionBtn"),cont=document.getElementById("locationContinue"),points=page.querySelectorAll(".locationPoint");if(points[0]){const strong=points[0].querySelector("strong");if(strong)strong.textContent="His Home";}if(points[1]){const strong=points[1].querySelector("strong");if(strong)strong.textContent="Your Home";}if(distance)distance.textContent=`${miles.toFixed(2)} miles`;if(mode)mode.textContent=live?"Live location received 📍":"Using saved location";if(status)status.textContent=live?"Location ready ❤️":"Live location unavailable — using saved location.";if(btn)btn.classList.add("hidden");if(cont)cont.classList.remove("hidden");if(typeof showPage==="function")showPage("locationPage");}
function requestHerLocation(){if(prewarmedHerLocation){renderLocationScene(prewarmedHerLocation,true);return;}renderLocationScene(HER_FALLBACK_LOCATION,false);if(!navigator.geolocation)return;navigator.geolocation.getCurrentPosition(p=>{prewarmedHerLocation={lat:p.coords.latitude,lng:p.coords.longitude};renderLocationScene(prewarmedHerLocation,true);},e=>console.warn("Location permission not granted:",e.message),{enableHighAccuracy:false,timeout:5000,maximumAge:300000});}
function prepareLocationPermission(){if(!navigator.geolocation)return Promise.resolve(false);return new Promise(resolve=>{navigator.geolocation.getCurrentPosition(p=>{prewarmedHerLocation={lat:p.coords.latitude,lng:p.coords.longitude};resolve(true);},e=>{console.warn("Location permission not granted:",e.message);resolve(false);},{enableHighAccuracy:false,timeout:5000,maximumAge:300000});});}
function startLocationScene(){requestHerLocation();}
console.log("📍 location.js loaded — instant fallback ready");