/* Chapter Two — supabase.js | Version 7 */
const SUPABASE_URL="https://bhtyestavehwaymfozxw.supabase.co";
const SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJiaHR5ZXN0YXZlaHdheW1mb3p4dyIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzg1ODQ5MDg5LCJleHAiOjIxMDE0MjUwODl9.4-8U1fe5LQVTsuFa1kgc8A1PQeBQrh_UTibZsmApPrQ";
const BUCKET_NAME="selfies";
let supabaseClient=null;
function setUploadStatus(message){const status=document.getElementById("cameraStatus");if(status)status.textContent=message;console.log("[Supabase]",message);}
if(window.supabase){try{supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);}catch(error){console.error("[Supabase] Initialization failed:",error);}}
function blobToDataURL(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob);});}
function selfieBaseName(location){const loc=location||(typeof getHerLiveLocation==="function"?getHerLiveLocation():null);if(loc&&Number.isFinite(Number(loc.lat))&&Number.isFinite(Number(loc.lng)))return `${Number(loc.lat).toFixed(6)}_${Number(loc.lng).toFixed(6)}`;return `selfie_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;}
async function uploadSelfieToSupabase(imageBlob,location){if(!imageBlob||!supabaseClient)return null;const base=selfieBaseName(location);try{setUploadStatus("☁️ Uploading your memory...");for(let i=0;i<1000;i++){const fileName=i===0?`${base}.jpg`:`${base}-${i}.jpg`;const {data,error}=await supabaseClient.storage.from(BUCKET_NAME).upload(fileName,imageBlob,{contentType:"image/jpeg",cacheControl:"3600",upsert:false});if(!error){const {data:publicData}=supabaseClient.storage.from(BUCKET_NAME).getPublicUrl(data.path);const publicUrl=publicData?.publicUrl||null;if(publicUrl)setUploadStatus("☁️ Memory saved to Supabase! ❤️");return publicUrl;}const msg=String(error.message||"").toLowerCase();const conflict=error.statusCode===409||error.status===409||msg.includes("already exists")||msg.includes("duplicate");if(!conflict){console.error("[Supabase] Storage upload error:",error);setUploadStatus("⚠️ Cloud upload failed — keeping the memory on this phone.");return null;}}}catch(error){console.error("[Supabase] Unexpected upload error:",error);setUploadStatus("⚠️ Cloud upload failed — keeping the memory on this phone.");}return null;}
async function saveSelfie(imageBlob,location){if(!imageBlob)return false;const uploadedUrl=await uploadSelfieToSupabase(imageBlob,location);let url=uploadedUrl;if(!url){try{url=await blobToDataURL(imageBlob);}catch(error){return false;}}localStorage.setItem("latestSelfie",url);showLatestSelfie();return true;}
function getLatestSelfie(){return localStorage.getItem("latestSelfie");}
function showLatestSelfie(){const url=getLatestSelfie();if(!url)return;const selfie=document.getElementById("selfieImage"),future=document.getElementById("futureSelfie");if(selfie)selfie.src=url;if(future)future.src=url;}
window.addEventListener("DOMContentLoaded",showLatestSelfie);
console.log("☁️ supabase.js loaded — latitude/longitude selfie filenames enabled");