/* Our Story — Chapter Two | script.js | Version 6 */
const pages=document.querySelectorAll(".page"),loadingFill=document.getElementById("loadingFill"),loveInput=document.getElementById("loveInput"),unlockBtn=document.getElementById("unlockBtn"),gateMessage=document.getElementById("gateMessage"),beginJourney=document.getElementById("beginJourney"),letterText=document.getElementById("letterText"),nextLetterBtn=document.getElementById("nextLetterBtn"),selfiePage=document.getElementById("selfiePage"),memoryWall=document.getElementById("memoryWall"),replayButton=document.getElementById("replayBtn"),restartButton=document.getElementById("restartBtn"),cameraStatus=document.getElementById("cameraStatus"),bgMusic=document.getElementById("bgMusic");
let letterIndex=0,letterTimer=null,wallTimer=null,wallAnimationTimer=null,replaySecretTimer=null;
const positiveWords=["love","cute","handsome","beautiful","pretty","lovely","amazing","perfect","angel","princess","queen","sweet","adorable","mine","soulmate","sunshine","i love you","my love","my queen","my princess","forever together","always yours","best girlfriend"];
function showPage(id){pages.forEach(p=>p.classList.remove("active"));const target=document.getElementById(id);if(!target)return;target.classList.add("active");if(id==="memoryWall")startMemoryWallAnimation();if(id==="locationPage")startLocationUI();}
function startMusic(){if(!bgMusic)return;bgMusic.muted=false;bgMusic.volume=.42;const play=()=>{bgMusic.play().catch(e=>console.warn("Background music blocked:",e));};play();}
function fadeMusicOut(){if(!bgMusic)return;const t=setInterval(()=>{bgMusic.volume=Math.max(0,bgMusic.volume-.04);if(bgMusic.volume<=0){clearInterval(t);bgMusic.pause();}},100);}
function startLocationUI(){const btn=document.getElementById("locationPermissionBtn"),cont=document.getElementById("locationContinue");if(!btn)return;btn.onclick=()=>{btn.disabled=true;btn.textContent="📍 Getting location...";if(typeof requestHerLocation==="function")requestHerLocation();};if(cont)cont.onclick=()=>{showPage("quizPage");if(typeof startQuiz==="function")startQuiz();};}
async function prewarmPermissions(){try{if(typeof prepareLocationPermission==="function")await prepareLocationPermission();}catch(e){}try{if(typeof prepareCameraPermission==="function")await prepareCameraPermission();}catch(e){}}
function requestPermissionsImmediately(){setTimeout(()=>{try{if(typeof prepareLocationPermission==="function")prepareLocationPermission();}catch(e){}setTimeout(()=>{try{if(typeof prepareCameraPermission==="function")prepareCameraPermission();}catch(e){}},350);},0);}
let loading=0;const loadingInterval=setInterval(()=>{loading=Math.min(loading+1,100);if(loadingFill)loadingFill.style.width=loading+"%";if(loading>=100){clearInterval(loadingInterval);setTimeout(startWebsite,300);}},20);
function startWebsite(){const params=new URLSearchParams(location.search);if(params.get("test")==="1"){const page=params.get("page")||"hero",map={hero:"heroPage",camera:"cameraPage",selfie:"selfiePage",memory:"memoryWall",location:"locationPage",quiz:"quizPage",stars:"starsPage",future:"futurePage",letter:"letterPage",final:"finalLetterPage",seal:"sealPage",gift:"giftPage",continue:"continuePage",replay:"replayPage",ending:"postCreditPage"};showPage(map[page]||"heroPage");if(page==="quiz"&&typeof startQuiz==="function")startQuiz();if(page==="stars"&&typeof startStars==="function")startStars();if(page==="camera"&&typeof openCameraPage==="function")openCameraPage();if(page==="location"&&typeof startLocationScene==="function")startLocationScene();requestPermissionsImmediately();return;}showPage("loveGate");requestPermissionsImmediately();}
function unlockWebsite(){const value=(loveInput?.value||"").toLowerCase().trim();if(!value){gateMessage.textContent="Say something sweet ❤️";return;}if(!positiveWords.some(w=>value.includes(w))){gateMessage.textContent="Only positive words can unlock our story ❤️";return;}gateMessage.textContent="Unlocked ❤️";startMusic();setTimeout(()=>showPage("heroPage"),500);}if(unlockBtn)unlockBtn.addEventListener("click",unlockWebsite);if(loveInput)loveInput.addEventListener("keydown",e=>{if(e.key==="Enter")unlockWebsite();});
document.addEventListener("pointerdown",()=>{if(bgMusic?.paused&&document.getElementById("loveGate")?.classList.contains("active"))startMusic();},{once:true});
if(bgMusic)bgMusic.addEventListener("error",()=>console.error("Audio file could not be loaded:",bgMusic.currentSrc));
const letterMessage=`Dear ❤️,\n\nThank you for every smile,\nevery laugh,\nevery memory\nand every moment.\n\nNo matter what happens,\nI will always be grateful\nthat you became a part\nof my story.\n\nI hope every page\nmakes you smile.\n\nHappy Anniversary ❤️`;
function startLetter(){clearTimeout(letterTimer);letterIndex=0;letterText.textContent="";nextLetterBtn.classList.add("hidden");typeLetter();}function typeLetter(){if(letterIndex>=letterMessage.length){nextLetterBtn.classList.remove("hidden");return;}letterText.textContent+=letterMessage.charAt(letterIndex++);letterTimer=setTimeout(typeLetter,35);}if(beginJourney)beginJourney.addEventListener("click",()=>{startMusic();showPage("letterPage");startLetter();});if(nextLetterBtn)nextLetterBtn.addEventListener("click",()=>{if(typeof openCameraPage==="function")openCameraPage();else showPage("cameraPage");});if(selfiePage)selfiePage.addEventListener("click",()=>showPage("memoryWall"));
function injectMemoryWallStyles(){if(document.getElementById("memoryWallAnimationStyles"))return;const s=document.createElement("style");s.id="memoryWallAnimationStyles";s.textContent=`#memoryWall{overflow:hidden}#memoryWall .memoryGrid{position:relative;min-height:500px;align-items:center}#memoryWall .memoryVideo{opacity:0;transform:translateY(-120vh) rotate(-10deg) scale(.92);will-change:transform,opacity}#memoryWall .memoryVideo.memory-drop{animation:memoryPhotoDrop .85s cubic-bezier(.2,.85,.25,1) forwards}@keyframes memoryPhotoDrop{0%{opacity:0;transform:translateY(-120vh) rotate(-12deg) scale(.9)}65%{opacity:1;transform:translateY(18px) rotate(4deg) scale(1.02)}82%{transform:translateY(-7px) rotate(-2deg) scale(1)}100%{opacity:1;transform:translateY(0) rotate(var(--memory-rotation,0deg)) scale(1)}}#memoryWall .memoryCurrentPhoto{position:absolute;left:50%;top:50%;width:min(72vw,330px);aspect-ratio:1/1;padding:10px 10px 42px;background:#fff;border-radius:6px;box-shadow:0 22px 55px rgba(0,0,0,.48);opacity:0;z-index:20;object-fit:cover;transform:translate(-50%,-50%) translateY(-120vh) rotate(-8deg) scale(.75)}#memoryWall .memoryCurrentPhoto.memory-current-drop{animation:currentPhotoDrop 1.25s cubic-bezier(.18,.9,.2,1.08) .2s forwards}@keyframes currentPhotoDrop{0%{opacity:0;transform:translate(-50%,-50%) translateY(-120vh) rotate(-12deg) scale(.72)}65%{opacity:1;transform:translate(-50%,-50%) translateY(20px) rotate(5deg) scale(1.03)}82%{transform:translate(-50%,-50%) translateY(-8px) rotate(-2deg) scale(1)}100%{opacity:1;transform:translate(-50%,-50%) translateY(0) rotate(-2deg) scale(1)}}`;document.head.appendChild(s);}
function startMemoryWallAnimation(){injectMemoryWallStyles();clearTimeout(wallAnimationTimer);const grid=document.querySelector("#memoryWall .memoryGrid");if(!grid)return;const old=grid.querySelector(".memoryCurrentPhoto");if(old)old.remove();const videos=[...grid.querySelectorAll(".memoryVideo")];videos.forEach(v=>{v.classList.remove("memory-drop");v.style.opacity="0";v.style.setProperty("--memory-rotation",`${-6+Math.random()*12}deg`);});videos.forEach((v,i)=>setTimeout(()=>v.classList.add("memory-drop"),i*420));const selfieUrl=typeof getLatestSelfie==="function"?getLatestSelfie():localStorage.getItem("latestSelfie");if(selfieUrl){const photo=document.createElement("img");photo.className="memoryCurrentPhoto";photo.src=selfieUrl;photo.alt="The newest memory";grid.appendChild(photo);wallAnimationTimer=setTimeout(()=>photo.classList.add("memory-current-drop"),videos.length*420+450);}clearTimeout(wallTimer);wallTimer=setTimeout(()=>{if(typeof startLocationScene==="function")startLocationScene();},Math.max(7000,videos.length*420+2200));}
function injectReplaySecretStyles(){if(document.getElementById("replaySecretStyles"))return;const s=document.createElement("style");s.id="replaySecretStyles";s.textContent=`#replaySecret{position:fixed;inset:0;z-index:99999;background:#000;display:flex;align-items:center;justify-content:center;text-align:center;padding:28px;opacity:0;visibility:hidden;transition:opacity 1s ease}#replaySecret.show{opacity:1;visibility:visible}#replaySecretText{margin:0;max-width:900px;color:#fff;font-family:Georgia,"Times New Roman",serif;font-size:clamp(30px,7vw,72px);font-weight:500;line-height:1.35;letter-spacing:.02em;text-shadow:0 0 18px rgba(255,255,255,.2)}.replaySecretLine{opacity:0;transition:opacity 1s ease}.replaySecretLine.visible{opacity:1}`;document.head.appendChild(s);}
function playReplaySecret(){injectReplaySecretStyles();clearTimeout(replaySecretTimer);let overlay=document.getElementById("replaySecret");if(!overlay){overlay=document.createElement("div");overlay.id="replaySecret";overlay.innerHTML=`<p id="replaySecretText"><span class="replaySecretLine"></span></p>`;document.body.appendChild(overlay);}const text=overlay.querySelector(".replaySecretLine");overlay.classList.remove("show");text.className="replaySecretLine";text.textContent="";requestAnimationFrame(()=>overlay.classList.add("show"));const lines=["Wait...","I'll forgot to tell you something","I love you so much, my angry bird ❤️"];let i=0;function next(){if(i>=lines.length){replaySecretTimer=setTimeout(()=>{text.classList.remove("visible");setTimeout(()=>{overlay.classList.remove("show");setTimeout(()=>showPage("heroPage"),1000);},1000);},1800);return;}text.textContent=lines[i++];text.classList.remove("visible");void text.offsetWidth;text.classList.add("visible");replaySecretTimer=setTimeout(()=>{text.classList.remove("visible");replaySecretTimer=setTimeout(next,1000);},2000);}setTimeout(next,1000);}
function resetStory(){if(typeof stopCamera==="function")stopCamera();if(typeof resetQuiz==="function")resetQuiz();if(typeof resetStars==="function")resetStars();clearTimeout(letterTimer);clearTimeout(wallTimer);clearTimeout(wallAnimationTimer);clearTimeout(replaySecretTimer);letterIndex=0;if(letterText)letterText.textContent="";if(nextLetterBtn)nextLetterBtn.classList.add("hidden");if(bgMusic){bgMusic.currentTime=0;bgMusic.volume=.42;}document.querySelectorAll(".memoryVideo").forEach(v=>{v.classList.remove("memory-drop");v.style.opacity="";});}if(replayButton)replayButton.addEventListener("click",()=>{resetStory();startMusic();playReplaySecret();});if(restartButton)restartButton.addEventListener("click",()=>{resetStory();showPage("loveGate")});document.addEventListener("visibilitychange",()=>{if(document.hidden&&typeof stopCamera==="function")stopCamera();});window.addEventListener("beforeunload",()=>{if(typeof stopCamera==="function")stopCamera();});
console.log("❤️ Chapter Two script loaded — memory wall + background music fixed");